/**
 * Scan-based auto-import for @velkin/vue (unplugin-vue-components).
 * Auto-generated by scripts/post-process-wrappers.js – do not edit the array by hand.
 */

const VELKIN_UI_COMPONENTS = [
  'VuAccordion',
  'VuAccordionItem',
  'VuAdaptiveBar',
  'VuAdaptiveItem',
  'VuAlert',
  'VuAppbar',
  'VuAvatar',
  'VuAvatarGroup',
  'VuBadge',
  'VuBreadcrumb',
  'VuBreadcrumbItem',
  'VuButton',
  'VuButtonGroup',
  'VuCard',
  'VuCarousel',
  'VuCarouselItem',
  'VuCheckbox',
  'VuCheckboxGroup',
  'VuChip',
  'VuColorArea',
  'VuColorPicker',
  'VuColorSlider',
  'VuColorSwatch',
  'VuColorSwatchPicker',
  'VuCombobox',
  'VuConfigProvider',
  'VuCounter',
  'VuDialog',
  'VuDivider',
  'VuDrawer',
  'VuDropdown',
  'VuDropdownItem',
  'VuForm',
  'VuIcon',
  'VuImage',
  'VuInput',
  'VuList',
  'VuListitem',
  'VuNavPanel',
  'VuNavbar',
  'VuNotificationProvider',
  'VuOtp',
  'VuOverlay',
  'VuPagination',
  'VuPopover',
  'VuProgress',
  'VuRadio',
  'VuRadioGroup',
  'VuRange',
  'VuSerial',
  'VuSkeleton',
  'VuSkeletonLoader',
  'VuSlider',
  'VuSpeeddial',
  'VuSpinner',
  'VuStepItem',
  'VuSteps',
  'VuSwitch',
  'VuTab',
  'VuTabItem',
  'VuThemeProvider',
  'VuThemeSwitcher',
  'VuTooltip',
  'VuVideo',
];

const SET = new Set(VELKIN_UI_COMPONENTS);

export function isVelkinUIComponent(name) {
  return SET.has(name);
}

export function VelkinUIVueResolver(options = {}) {
  const packageName = options.packageName ?? '@velkin/vue';
  return (componentName) => {
    if (!SET.has(componentName)) return;
    return { name: componentName, from: packageName };
  };
}
