import vue from "rollup-plugin-vue";
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import typescript from "rollup-plugin-typescript2";
import path from "path";
import { copyFileSync, readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export default {
  input: path.join(__dirname, "src", "index.ts"),
  output: {
    dir: "dist",
    format: "esm",
    sourcemap: true,
    preserveModules: true,
    preserveModulesRoot: "src",
    entryFileNames: "[name].js",
    chunkFileNames: "[name]-[hash].js",
  },
  plugins: [
    vue({ css: true, template: { isProduction: true } }),
    typescript({
      tsconfig: "./tsconfig.json",
      useTsconfigDeclarationDir: true,
      clean: true,
      // Default rpt2 include uses micromatch `*.ts+(|x)` which picomatch does not treat as .ts/.tsx;
      // the filter then skips all files, so Vue SFC `?vue&type=script&lang.ts` chunks are never
      // transformed and Rollup parses raw TS (e.g. `export interface`) as JavaScript and fails.
      include: ["**/*.ts", "**/*.tsx", "**/*.cts", "**/*.mts"],
      // ensure .d.ts are emitted to dist/
      tsconfigOverride: {
        compilerOptions: {
          declaration: true,
          declarationMap: false,
          emitDeclarationOnly: false,
          declarationDir: "dist",
          rootDir: "src",
          outDir: "dist",
        },
      },
      check: false,
    }),
    resolve({
      extensions: [".vue", ".ts", ".js"],
      dedupe: ["vue", "@velkin/ui"],
    }),
    commonjs(),
    {
      name: "emit-vue-global-components-dts",
      closeBundle() {
        // src/global-components.d.ts is generated by scripts/post-process-wrappers.js (not hand-edited).
        const src = path.join(__dirname, "src/global-components.d.ts");
        const dest = path.join(__dirname, "dist/global-components.d.ts");
        copyFileSync(src, dest);
        const indexDts = path.join(__dirname, "dist/index.d.ts");
        let body = readFileSync(indexDts, "utf8");
        const ref = '/// <reference path="./global-components.d.ts" />\n';
        if (!body.includes("global-components.d.ts")) {
          writeFileSync(indexDts, ref + body);
        }
      },
    },
  ],
  external: (id) => !id.startsWith(".") && !path.isAbsolute(id),
  onwarn: (warning, warn) => {
    if (["CIRCULAR_DEPENDENCY", "THIS_IS_UNDEFINED"].includes(warning.code)) return;
    warn(warning);
  },
};
