/**
 * Auto-generated by scripts/sync-core-package.mjs
 */
const VELKIN_UI_COMPONENTS = [
  'Accordion',
  'AccordionItem',
  'AdaptiveBar',
  'AdaptiveItem',
  'Alert',
  'Appbar',
  'Avatar',
  'AvatarGroup',
  'Badge',
  'Breadcrumb',
  'BreadcrumbItem',
  'Button',
  'ButtonGroup',
  'Card',
  'Carousel',
  'CarouselItem',
  'Checkbox',
  'CheckboxGroup',
  'Chip',
  'ColorArea',
  'ColorPicker',
  'ColorSlider',
  'ColorSwatch',
  'ColorSwatchPicker',
  'Combobox',
  'ConfigProvider',
  'Counter',
  'Dialog',
  'Divider',
  'Drawer',
  'Dropdown',
  'DropdownItem',
  'Form',
  'Icon',
  'Image',
  'Input',
  'List',
  'ListItem',
  'NavPanel',
  'Navbar',
  'Notification',
  'Otp',
  'Overlay',
  'Pagination',
  'Popover',
  'Progress',
  'Radio',
  'RadioGroup',
  'Range',
  'Serial',
  'Skeleton',
  'SkeletonLoader',
  'Slider',
  'Speeddial',
  'Spinner',
  'StepItem',
  'Steps',
  'Switch',
  'Tab',
  'TabItem',
  'ThemeProvider',
  'ThemeSwitcher',
  'Tooltip',
  'Video',
];
const SET = new Set(VELKIN_UI_COMPONENTS);
export function isVelkinUIComponent(name) { return SET.has(name); }
export function VelkinUIMainResolver(options = {}) {
  const packageName = options.packageName ?? '@velkin/ui';
  return (componentName) => {
    if (!SET.has(componentName)) return;
    return { name: componentName, from: packageName };
  };
}
export const VELKIN_UI_TAG_NAMES = new Set(
  VELKIN_UI_COMPONENTS.map((name) =>
    name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/^Vu/, 'vu-').toLowerCase(),
  ),
);
export function getCoreImportPath(tag, packageName = '@velkin/ui') {
  return `${packageName}/${tag}`;
}
