/**
 * Scan-based auto-import for @velkin/react (unplugin-react-components).
 * Auto-generated by scripts/post-process-wrappers.js – do not edit the array by hand.
 */

const VELKIN_UI_COMPONENTS = [
  'VuAccordion',
  'VuAccordionItem',
  'VuAdaptiveBar',
  'VuAdaptiveItem',
  'VuAlert',
  'VuAppbar',
  'VuAvatar',
  'VuAvatarGroup',
  'VuBadge',
  'VuBreadcrumb',
  'VuBreadcrumbItem',
  'VuButton',
  'VuButtonGroup',
  'VuCard',
  'VuCarousel',
  'VuCarouselItem',
  'VuCheckbox',
  'VuCheckboxGroup',
  'VuChip',
  'VuColorArea',
  'VuColorPicker',
  'VuColorSlider',
  'VuColorSwatch',
  'VuColorSwatchPicker',
  'VuCombobox',
  'VuConfigProvider',
  'VuCounter',
  'VuDialog',
  'VuDivider',
  'VuDrawer',
  'VuDropdown',
  'VuDropdownItem',
  'VuForm',
  'VuIcon',
  'VuImage',
  'VuInput',
  'VuList',
  'VuListitem',
  'VuNavPanel',
  'VuNavbar',
  'VuNotificationProvider',
  'VuOtp',
  'VuOverlay',
  'VuPagination',
  'VuPopover',
  'VuProgress',
  'VuRadio',
  'VuRadioGroup',
  'VuRange',
  'VuSerial',
  'VuSkeleton',
  'VuSkeletonLoader',
  'VuSlider',
  'VuSpeeddial',
  'VuSpinner',
  'VuStepItem',
  'VuSteps',
  'VuSwitch',
  'VuTab',
  'VuTabItem',
  'VuThemeProvider',
  'VuThemeSwitcher',
  'VuTooltip',
  'VuVideo',
];

export function VelkinUIReactResolver(options = {}) {
  const packageName = options.packageName ?? '@velkin/react';
  return () =>
    VELKIN_UI_COMPONENTS.map((name) => ({
      name,
      from: packageName,
      type: 'Export',
      originalName: name,
    }));
}

export function VelkinUIReactResolverList(options = {}) {
  const packageName = options.packageName ?? '@velkin/react';
  return VELKIN_UI_COMPONENTS.map((name) => ({
    name,
    from: packageName,
    type: 'Export',
    originalName: name,
  }));
}
